// Converts snarkjs build/verification_key.json into a Rust file for groth16-solana 0.2.0.
// Output: ../programs/zkclaim/src/verifying_key.rs (or the path given as argv[2]).
// Note: groth16-solana 0.2.0 on crates.io spells the field `vk_gamme_g2` (sic).
const fs = require("fs");
const path = require("path");
const { be32 } = require("./solana-format");

const vk = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "build", "verification_key.json")));
const out = process.argv[2] || path.join(__dirname, "..", "..", "programs", "zkclaim", "src", "verifying_key.rs");

const bytes = (arr) => "[" + Array.from(arr).join(", ") + "]";
const g1 = (p) => bytes([...be32(p[0]), ...be32(p[1])]);
// snarkjs G2 = [[x.c0, x.c1], [y.c0, y.c1], [1, 0]] -> x.c1 || x.c0 || y.c1 || y.c0
const g2 = (p) => bytes([...be32(p[0][1]), ...be32(p[0][0]), ...be32(p[1][1]), ...be32(p[1][0])]);

const rs = `// GENERATED by circuits/scripts/vk-to-rust.js from circuits/build/verification_key.json.
// Do not edit by hand. Regenerate after every circuit change / trusted setup.
use groth16_solana::groth16::Groth16Verifyingkey;

pub const NR_PUBLIC_INPUTS: usize = ${vk.nPublic};

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: ${vk.IC.length},
    vk_alpha_g1: ${g1(vk.vk_alpha_1)},
    vk_beta_g2: ${g2(vk.vk_beta_2)},
    vk_gamme_g2: ${g2(vk.vk_gamma_2)},
    vk_delta_g2: ${g2(vk.vk_delta_2)},
    vk_ic: &[
${vk.IC.map((p) => "        " + g1(p) + ",").join("\n")}
    ],
};
`;

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, rs);
console.log("wrote", out, `(${vk.nPublic} public inputs, ${vk.IC.length} IC points)`);
